<a href="https://colab.research.google.com/github/Sev-RyanLeo/Linear-Algebra-58019/blob/main/Application.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

November 17

In [8]:
import numpy as np
A=np.array([[4,3,2],[-2,2,3],[3,-5,2]])
B=np.array([[25],[-10],[-4]])
print(A,"\n \n",B)

x=np.linalg.solve(A,B)

print("\n Answer: \n",x)

[[ 4  3  2]
 [-2  2  3]
 [ 3 -5  2]] 
 
 [[ 25]
 [-10]
 [ -4]]

 Answer: 
 [[ 5.]
 [ 3.]
 [-2.]]


**using scipy.linalg**

In [11]:
import numpy as np
from scipy.linalg import solve
A=np.array([[4,3,2],[-2,2,3],[3,-5,2]])
B=np.array([[25],[-10],[-4]])
print(A,"\n \n",B)

x=solve(A,B)

print("\n Answer: \n",x)

[[ 4  3  2]
 [-2  2  3]
 [ 3 -5  2]] 
 
 [[ 25]
 [-10]
 [ -4]]

 Answer: 
 [[ 5.]
 [ 3.]
 [-2.]]
