<a href="https://colab.research.google.com/github/Sev-RyanLeo/Linear-Algebra-58019/blob/main/Coding_Activity_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
A=np.array([[4,10,8],[10,26,26],[8,26,61]])
print(A)
invA= np.linalg.inv(A)
print(invA)


B=np.array([[44],[128],[214]])
print(B)
X=np.linalg.inv(A).dot(B)
print("\n Values of  x,y,z respectively")
print(X)

#to check if answer is correct
Z=np.dot(A,X)
print("\n Checking \n",Z)


[[ 4 10  8]
 [10 26 26]
 [ 8 26 61]]
[[ 25.27777778 -11.16666667   1.44444444]
 [-11.16666667   5.          -0.66666667]
 [  1.44444444  -0.66666667   0.11111111]]
[[ 44]
 [128]
 [214]]

 Values of  x,y,z respectively
[[-8.]
 [ 6.]
 [ 2.]]

 Checking 
 [[ 44.]
 [128.]
 [214.]]
