<a href="https://colab.research.google.com/github/Sev-RyanLeo/Linear-Algebra-58019/blob/main/Determinant_of_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np                            #importing of library for array syntax access
A=np.array([[1,2,-1],[4,6,-2],[-1,3,3]])      #defining of array and its values
print(A)                                      #printing of array values

print("Determinant of array A:")               #printing of label
print(round(np.linalg.det(A)))                #acquiring and printing of array A

[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]
Determinant of array A:
-14
