<a href="https://colab.research.google.com/github/Sev-RyanLeo/Linear-Algebra-58019/blob/main/Eigenvalue_and_Eigenvectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from numpy.linalg import eig

A = np.array([[-12,3],[4,1]])
print(A)

inv_A = np.linalg.inv(A)
print(inv_A)

B = np.array([[0],[0]])
print(B)

X = np.dot(inv_A,B)
print(X)
#X = solve(A,B)
#print(X)

[[-12   3]
 [  4   1]]
[[-0.04166667  0.125     ]
 [ 0.16666667  0.5       ]]
[[0]
 [0]]
[[0.]
 [0.]]


In [5]:
#Example 1
A = np.array([[-6,3],[4,5]])
print(A)

w,v = np.linalg.eig(A)
print("The eigenvalue/s is/are:",w)
print("The right eigenvectors are:",v)
#x = v.round()
#print(x) 

[[-6  3]
 [ 4  5]]
The eigenvalue/s is/are: [-7.  6.]
The right eigenvectors are: [[-0.9486833  -0.24253563]
 [ 0.31622777 -0.9701425 ]]


In [7]:
#Example 2
A = np.array([[2,2,4],[1,3,5],[2,3,4]])
print(A)
s,t = np.linalg.eig(A)
print(s.round())
print(t.round())
c = np.dot(A,t.round())
print(c)

[[2 2 4]
 [1 3 5]
 [2 3 4]]
[ 9.  1. -1.]
[[-1. -1. -0.]
 [-1.  1. -1.]
 [-1. -0.  1.]]
[[-8.  0.  2.]
 [-9.  2.  2.]
 [-9.  1.  1.]]
