<a href="https://colab.research.google.com/github/Sev-RyanLeo/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Final Exam



Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have? (30 points)

In [5]:
import numpy as np                                #importing appropriate library to be used
P1=np.array([[1,1,1],[1,0,4],[0,0,5]])            #creating the array and values setting based on coeffecients
print(P1)                                         #printing of array



P1A=np.array([[89],[89],[95]])                    #creating the array and values setting based on constants
print(P1A)                                        #print array  
Roots=np.linalg.inv(P1).dot(P1A)                  #getting roots through dot product of acquire values  
print("\n \nValues of  A,B,C respectively")       #printing label
print(Roots)                                      #printing roots

#to check if answer is correct
Z=np.dot(P1,Roots)                                #checking legitimacy of acquired values
print("\n Checking... \n",Z)                      #printing validation proof

[[1 1 1]
 [1 0 4]
 [0 0 5]]
[[89]
 [89]
 [95]]

 
Values of  A,B,C respectively
[[13.]
 [57.]
 [19.]]

 Checking... 
 [[89.]
 [89.]
 [95.]]


Problem 2. Solve each system: (30 points)

3x - y + z = 5

9x - 3y +3z = 15

-12x +4y -4z = -20 

A non-invertible matrix is known as a singular matrix. This indicates that the system of equations trying to be solved lacks a unique solution, which linalg.solve can't handle. Singularity will happen if duplicate columns have a correlation value of 1.0. The given has common coeffecients ([[3,-1,1],[9,-3,3],[-12,4,-4]]) of 3, resulting into singularity error when inversing



In [25]:
import numpy as np
Z = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(Z,"\n")
d,c = np.linalg.eig(Z)
print("Eigenvalues:",d,"\n")
print("Eigenvectors :","\n",c.round())




[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]] 

Eigenvalues: [-1.  3.  2.] 

Eigenvectors : 
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
