<a href="https://colab.research.google.com/github/Sev-RyanLeo/Linear-Algebra-58019/blob/main/Linear_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Example

In [ ]:
import numpy as np
A=np.array([[4,3],[-5,9]])
print(A)

invA= np.linalg.inv(A)
print(invA)


B=np.array([[20],[26]])
print(B)
X=np.linalg.inv(A).dot(B)
print(X)


[[ 4  3]
 [-5  9]]
[[ 0.17647059 -0.05882353]
 [ 0.09803922  0.07843137]]
[[2.]
 [4.]]


In [ ]:
dot=np.dot(invA,B)
print(dot)

[[2.]
 [4.]]


Sample Problem

4x+3y+2z=25

-2x+2y+3z=-10

3x-5y+2z=-4


In [ ]:
import numpy as np
A=np.array([[4,3,2],[-2,2,3],[3,-5,2]])
print(A)

invA= np.linalg.inv(A)
print(invA)


B=np.array([[25],[-10],[-4]])
print(B)
X=np.linalg.inv(A).dot(B)
print(X)

[[ 4  3  2]
 [-2  2  3]
 [ 3 -5  2]]
[[ 0.15447154 -0.1300813   0.04065041]
 [ 0.10569106  0.01626016 -0.1300813 ]
 [ 0.03252033  0.23577236  0.11382114]]
[[ 25]
 [-10]
 [ -4]]
[[ 5.]
 [ 3.]
 [-2.]]


Suppose a market seller sold 20 apple and 10 oranges in one day for a total of 350 pesos. The next day he sold 17 apple and 22 orange for 500 pesos. If the prices of the fruits remained unchanged on both of the days, what was the price of one apple and one orange?

In [ ]:
A=np.array([[20,10],[17,22]])
print(A)
invA= np.linalg.inv(A)
print(invA)

B=np.array([[350],[500]])
print(B)

X=np.dot(invA,B)
print(X)


[[20 10]
 [17 22]]
[[ 0.08148148 -0.03703704]
 [-0.06296296  0.07407407]]
[[350]
 [500]]
[[10.]
 [15.]]


To check if the answer is correct

In [ ]:
Z=np.dot(A,X)
print(Z)

[[350.]
 [500.]]
