<a href="https://colab.research.google.com/github/Sev-RyanLeo/Linear-Algebra-58019/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Python program to inverse

In [55]:
import numpy as np
from numpy.linalg import inv
M=np.array([[1,2],[4,7]])
invM=np.linalg.inv(M)
print(invM)

[[-7.  2.]
 [ 4. -1.]]


In [56]:
C=np.dot(M,invM)
print(C)

[[1. 0.]
 [0. 1.]]


In [44]:
##Python Program to tranpose a 3x3 Matrix A=([6,1,1],[4,-2,5],[2,8,7])
Emis=np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(Emis)
Artis=np.transpose(Emis)
print(Artis)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


In [51]:
#Python Program to inverse a 3x3 Matrix A=([6,1,1],[4,-2,5],[2,8,7])
x=np.array([[6,1,1],[4,-2,5],[2,8,7]])
y=np.linalg.inv(x)
print(invArf)

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [52]:
#Dot Product of Arf and invArf
z=np.dot(x,y)
print(z)

[[ 1.00000000e+00  0.00000000e+00  2.77555756e-17]
 [-1.38777878e-17  1.00000000e+00  1.38777878e-17]
 [-4.16333634e-17  1.38777878e-16  1.00000000e+00]]


#Python Exercise 3

In [59]:
import numpy as np                                        #importing of library 
A=np.array([[6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7]])    #defining or array
B=np.linalg.inv(A)                                        #inversing of array
print(B)                                                  #print of inversed


[[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]


In [60]:
C=np.transpose(A)     #transposing array
print(C)              #printing transposed array

[[ 6  4  2  3]
 [ 1 -2  8  1]
 [ 1  5  7  9]
 [ 3  1  6  7]]
