<a href="https://colab.research.google.com/github/Sev-RyanLeo/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Midterm Exam

Question 1. Create a Python code that displays a square matrix whose length is 5 (10 points)

In [16]:
import numpy as np                   #importing appropriate library to be used
Q1=np.full((5,5),1)                  #creating an array with np.full syntax - (np.full((rows,columns)),filler)
print("Square matrix with l=5 \n")   #printing label
print(Q1)                            #printing of the array

Square matrix with l=5 

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)



In [4]:
import numpy as np     #importing appropriate library to be used
Q2=np.eye(5)           #creating an array with np.eye syntax- np.eye(size)
print(Q2)              #printing of the array

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)

In [10]:
import numpy as np                       #importing appropriate library to be used
Q3=np.array([[1,2,3],[2,4,5],[3,5,8]])   #creating an array and values setting
print(Q3)                                #printing array
Q3trans=np.transpose(Q3)                 #checking if array is symmetric by transposing 
print("\n when transposed \n",Q3trans)   #printing transposed array

[[1 2 3]
 [2 4 5]
 [3 5 8]]

 when transposed 
 [[1 2 3]
 [2 4 5]
 [3 5 8]]


Question 4. What is the inverse of matrix C? Show your solution by python coding. (20 points)

In [13]:

import numpy as np                       #importing appropriate library to be used
Q4=np.array([[1,2,3],[2,3,3],[3,4,-2]])  #creating the array and values setting
Q4inv=np.linalg.inv(Q4)                  #inversing value using np.linalg.inv syntax
print(Q4inv)                             #printing of inversed array


[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)

In [19]:
import numpy as np                            #importing appropriate library to be used
Q5=np.array([[1,2,3],[2,3,3],[3,4,-2]])       #creating the array and values setting
print(Q5)                                     #printing array
print("\nThe determinant of the array :")     #printing of label
print(round(np.linalg.det(Q5)))               #getting and printing of determinant of array


[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]

The determinant of the array :
5


Question 6. Find the roots of the linear equations by showing its python codes (30 points)

5X1 + 4X2 + X3 = 3.4

10X1 + 9X2 + 4X3 = 8.8

10X1 + 13X2 + 15X3 = 19.2


In [20]:
import numpy as np                                #importing appropriate library to be used
Q6=np.array([[5,4,1],[10,9,4],[10,13,15]])        #creating the array and values setting based on coeffecients
print(Q6)                                         #printing of array
Q6inv= np.linalg.inv(Q6)                          #inversing array values


Q6B=np.array([[3.4],[8.8],[19.2]])                #creating the array and values setting based on constants
print(Q6B)                                        #print array  
Roots=np.linalg.inv(Q6).dot(Q6B)                  #getting roots through dot product of acquire values  
print("\n \nValues of  x,y,z respectively")       #printing label
print(Roots)                                      #printing roots

#to check if answer is correct
Z=np.dot(Q6,Roots)                                #checking legitimacy of acquired values
print("\n Checking \n",Z)                         #printing validation proof


[[ 5  4  1]
 [10  9  4]
 [10 13 15]]
[[ 3.4]
 [ 8.8]
 [19.2]]

 Values of  x,y,z respectively
[[0.2]
 [0.4]
 [0.8]]

 Checking 
 [[ 3.4]
 [ 8.8]
 [19.2]]
