<a href="https://colab.research.google.com/github/Sev-RyanLeo/Linear-Algebra-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Practical Lab Exam 1

In [31]:
import numpy as np

A=np.array(([1,2,3],[4,5,6]))
B = np.array ((([1,2],[3,4],[5,6])))
C = np.array ((([1,2,3],[4,5,6],[7,8,9])))
D = np.array (([1,2],[3,4]))


print("VALUES OF ALL ARRAYS: \n")
print(A)
print("\n")
print(B)
print("\n")
print(C)
print("\n")
print(D)
print("\n")
print("________________ \n")

#a. AB
print("AB \n")
cross=np.dot(A,B)
print(cross)

#b. D+D
print("________________ \n")
print("D+D \n")
sum=D+D
print(sum)

#c. 2C
print("________________ \n")
print("2C \n")
upscale=2*C
print(upscale)




VALUES OF ALL ARRAYS: 

[[1 2 3]
 [4 5 6]]


[[1 2]
 [3 4]
 [5 6]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 2]
 [3 4]]


________________ 

AB 

[[22 28]
 [49 64]]
________________ 

D+D 

[[2 4]
 [6 8]]
________________ 

2C 

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [30]:
#given equation expressed as matrix
import numpy as np
emis=np.array([5,3,-1])

print("Array: \n",emis,"\n")


print("Structure type: ",type(emis))
print("Data type: ", emis.dtype)
print("Shape: ", emis.shape)
print("Dimension: ", emis.ndim)


Array: 
 [ 5  3 -1] 

Structure type:  <class 'numpy.ndarray'>
Data type:  int64
Shape:  (3,)
Dimension:  1
