<a href="https://colab.research.google.com/github/Sev-RyanLeo/Linear-Algebra-58019/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Prelim Exam


Question 1

Create a 4 x 4 matrix whose diagonal elements are all one (1's). Name it as matrix "C". Show your solutions using Python codes and do not forget to label them on the Text Cell.

In [27]:
print("Question 1")   #printing of label
import numpy as np    #importing of library used for array matrices
C= np.eye((4))        #creation of matrix C with default value of 1 in diagonal
print(C)              #printing values of matrix C



Question 1
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Question 2

In relation to Question 1, show a solution that doubles all the values of each element. Show your solutions using Python codes and do not forget to label them on the Text Cell.

In [28]:
import numpy as np    #importing of library used for array matrices
C= np.eye((4))        #creation of matrix C with default value of 1 in diagonal
print("Question 2")   #printing of label
doubleC=C*2           #scaling value of C by 2 and assigning to another variable
print(doubleC)        #print of variable assigned for scaled up values



Question 2
[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


Question 3

Find the cross-product of matrices, A = [2,7,4] and B = [3,9,8]. Show your solutions using Python codes and do not forget to label them on the Text Cell.

In [29]:
import numpy as np                      #importing of library used for array matrices
A = np.array([2,7,4])                   #creation of Array A and assigning its values
B = np.array([3,9,8])                   #creation of Array B and assigning its values
cpAP= np.cross(A,B)                     #crossing A and B, then assigning its values to a new variable
print("Question 3")                     #printing of label
print("Cross Product of A and B: \n")   #printing of label
print(cpAP)                             #prinnting the variable containing cross-product of A and B

Question 3
Cross Product of A and B: 

[20 -4 -3]
