<a href="https://colab.research.google.com/github/Sev-RyanLeo/Linear-Algebra-58019/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Representing Vectors


In [2]:
import numpy as np

A=np.array([4,2])
B=np.array([2,-5])

print("Vector A is ", A)
print("Vector B is ", B )

Vector A is  [4 2]
Vector B is  [ 2 -5]


#Describing Vectors in NumPy


In [10]:
import numpy as np
ball1=np.array([1,2,3])
ball2=np.array([0,1,-1])
pool=np.array([ball1,ball2])
pool.shape
pool.ndim

2

In [15]:
u=np.array([[1,2,3],[4,5,6]])
u.shape #rows and columns (no. of rows, no. of columns)

(2, 3)

In [17]:
u=np.array([[1,2,3],[4,5,6]])
u.ndim #number of dimensions

2

In [18]:
u=np.array([[1,2,3],[4,5,6]])
u.size #number of components

6

#Space

##Vector spaces are mathematical objects that abstractly capture the geometry and algebra of linear equations


#Addition of Vector


In [34]:
import numpy as np
addend1=np.array([0,0,0])
addend2=np.array([1,1,0])
sum=addend1+addend2
print(sum)


[1 1 0]


In [35]:
import numpy as np
addend1=np.array([0,0,0])
addend2=np.array([1,1,0])
resultant = np.add(addend1,addend2)
print(resultant)

[1 1 0]


#Subtraction of Vector


In [26]:

difference=addend1-addend2
print(difference)


[-1 -1  0]


In [28]:

difference2 = np.subtract(addend1,addend2)
print(difference2)

[-1 -1  0]


#Scaling 

In [30]:
X= np.array([1,5,8,9])
S= 5*A1
print(S)

[ 5 25 40 45]


#Cross Product

In [36]:
import numpy as np

c1=np.array([2,3])
c2=np.array([1,7])
output=np.cross(c1,c2)
print(output)

11


In [38]:
import numpy as np

c3=np.array([2,3,4])
c4=np.array([1,7,1])
output2=np.cross(c3,c4)
print(output2)

[-25   2  11]


#Dot Product


In [41]:
dot1=np.dot(c1,c2)
print(dot1)

23


In [43]:
dot2=np.dot(c3,c4)
print(dot2)

27
