<a href="https://colab.research.google.com/github/Sev-RyanLeo/Linear-Algebra-58019/blob/main/Python_Activity_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and Its Operations

Array


In [29]:
import numpy as np
a= np.array([[-5,0],[4,1]])
print("Matrix A \n \n" ,a)
b= np.array([[6,-3],[2,3]])
print("\n Matrix B \n \n" ,b)
print("\nAddition of A and B \n \n" ,a+b)
print("\nDifference of B and A (b-a) \n \n", b-a)
print("\nDifference of A and B (a-b) \n \n", a-b)

Matrix A 
 
 [[-5  0]
 [ 4  1]]

 Matrix B 
 
 [[ 6 -3]
 [ 2  3]]

Addition of A and B 
 
 [[ 1 -3]
 [ 6  4]]

Difference of B and A (b-a) 
 
 [[11 -3]
 [-2  2]]

Difference of A and B (a-b) 
 
 [[-11   3]
 [  2  -2]]
