<a href="https://colab.research.google.com/github/Sev-RyanLeo/Linear-Algebra-58019/blob/main/Python_Activity_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and Its Operations

Array


In [13]:
import numpy as np
a= np.array([[-5,0],[4,1]])
print(a)
b= np.array([[6,-3],[2,3]])
print(b)

[[-5  0]
 [ 4  1]]
[[ 6 -3]
 [ 2  3]]


Sum of A and B

In [14]:
import numpy as np
a= np.array([[-5,0],[4,1]])
b= np.array([[6,-3],[2,3]])
print(a+b)

[[ 1 -3]
 [ 6  4]]


Difference of B and A (b-a)

In [15]:
import numpy as np
a= np.array([[-5,0],[4,1]])
b= np.array([[6,-3],[2,3]])
print(b-a)

[[11 -3]
 [-2  2]]


Difference of A and B (a-b)

In [16]:
import numpy as np
a= np.array([[-5,0],[4,1]])
b= np.array([[6,-3],[2,3]])
print(a-b)

[[-11   3]
 [  2  -2]]
