<a href="https://colab.research.google.com/github/Sev-RyanLeo/Linear-Algebra-58019/blob/main/Vectors_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix Algebra


Rectangular Matrix


In [4]:
#numphy
import numpy as np
a = np.array([1,2,3]) #This is an example of 1x3 matrix
print(a)

[1 2 3]


In [7]:
import numpy as np
b=np.array([[1,2,3],[4,5,6]]) #This is a 2x3 matrix
print(b)

[[1 2 3]
 [4 5 6]]


Square Matrix

In [10]:
import numpy as np
c= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
import numpy as np
d=np.full((3,3),7)
print(d)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [24]:
import numpy as np
c= np.array([[1,2,3],[4,5,6],[7,8,9]])
e=np.diagonal([[1,2,3],[4,5,6],[7,8,9]])
print(c)
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [26]:
import numpy as np
f= np.eye(3)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
import numpy as np
g=np.zeros((3,3))
print(g)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [31]:
import numpy as np
h= np.empty(0)
print(h)


[]


Addition of Matrix

In [33]:
import numpy as np
import numpy as np
d=np.full((3,3),7)
print(d+d)



[[14 14 14]
 [14 14 14]
 [14 14 14]]


Subtraction or Matrix

In [34]:
import numpy as np
d=np.full((3,3),7)
print(d-d)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
